export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SELECT_MENU = "SELECT_MENU";
export const MENU_ITEMS = {
  CHAT: "CHAT",
  CONTACTS: "CONTACTS",
};

export const RECEIVED_NEW_MESSAGE = "RECEIVED_NEW_MESSAGE";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
