export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const UPDATE_ADD_CONTACT_REQUESTS_RECEIVED =
  "UPDATE_ADD_CONTACT_REQUESTS_RECEIVED";
export const UPDATE_ADD_CONTACT_REQUESTS_SENT =
  "UPDATE_ADD_CONTACT_REQUESTS_SENT";
export const UPDATE_ADD_CONTACTS = "UPDATE_ADD_CONTACTS";

export const SELECT_MENU = "SELECT_MENU";
export const SELECT_CONTACT_MENU = "SELECT_CONTACT_MENU";
export const MENU_ITEMS = {
  CHAT: "CHAT",
  CONTACTS: "CONTACTS",
};
export const CONTACT_MENU_ITEMS = {
  FRIENDS: "FRIENDS",
  GROUPS: "GROUPS",
  ADD_CONTACT_REQUEST_RECEIVED: "ADD_CONTACT_REQUEST_RECEIVED",
  ADD_CONTACT_REQUEST_SENT: "ADD_CONTACT_REQUEST_SENT",
};

export const RECEIVED_NEW_MESSAGE = "RECEIVED_NEW_MESSAGE";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";

export const SEND_ADD_CONTACT_REQUEST_SUCCESS =
  "SEND_ADD_CONTACT_REQUEST_SUCCESS";
export const CANCEL_ADD_CONTACT_REQUEST_SUCCESS =
  "CANCEL_ADD_CONTACT_REQUEST_SUCCESS";
export const ACCEPT_ADD_CONTACT_REQUEST_SUCCESS =
  "ACCEPT_ADD_CONTACT_REQUEST_SUCCESS";
export const DECLINE_ADD_CONTACT_REQUEST_SUCCESS =
  "DECLINE_ADD_CONTACT_REQUEST_SUCCESS";
export const RECEIVED_ADD_CONTACT_REQUEST = "RECEIVED_ADD_CONTACT_REQUEST";
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";

export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const UPDATE_GROUPS = "UPDATE_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const REMOVE_GROUP = "REMOVE_GROUP";
export const MEMBER_LEAVE_GROUP = "MEMBER_LEAVE_GROUP";

export const UPDATE_CONVERSATIONS = "UPDATE_CONVERSATIONS";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
