export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";

export const SELECT_MENU = "SELECT_MENU";
export const MENU_ITEMS = {
  CHAT: "CHAT",
  CONTACTS: "CONTACTS",
};

export const RECEIVED_NEW_MESSAGE = "RECEIVED_NEW_MESSAGE";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
